format = '''[\[](bold green)$username$hostname $directory[\]](bold green)$git_branch$git_status$nix_shell$character'''

add_newline = false

[username]
show_always = true
style_user = "bold green"
format = '[$user]($style)'

[hostname]
ssh_only = false
style = "bold green"
format = '[@$hostname]($style)'

[directory]
style = "bold blue"
truncation_length = 6
format = '[$path]($style)'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold green)'

[git_branch]
symbol = ""
style = "bold yellow"
format = '([\[$branch\]]($style))'

[git_status]
style = "bold red"
format = '([\[$all_status$ahead_behind\]]($style))'

[nix_shell]
symbol = ""
style = "bold blue"
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = '[\(](bold cyan)[$name](bold cyan)[\)](bold cyan)'
# format = '[\[](bold green)[$symbol]($style)[\]](bold green)'

[cmd_duration]
min_time = 500
style = "bold yellow"
format = ' t:[$duration]($style)'




