# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ self, inputs, ... }: {
  flake.nixosHardware.laptop = { config, lib, pkgs, modulesPath, ... }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/mapper/luks-c8f9fa33-cf9a-4917-a621-b8b6a115e98d";
        fsType = "ext4";
      };

    boot.initrd.luks.devices."luks-c8f9fa33-cf9a-4917-a621-b8b6a115e98d".device = "/dev/disk/by-uuid/c8f9fa33-cf9a-4917-a621-b8b6a115e98d";

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/8A38-153F";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices = [ ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
