font_family JetBrainsMono Nerd Font

# background #161616

confirm_os_window_close 0

font_size 12.0

cursor_shape beam
cursor_beam_thickness 1.5
cursor_trail 3

window_margin_width 5

enable_audio_bell no

allow_remote_control yes

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
