# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ self, inputs, ... }: {
  flake.nixosHardware.pc = { config, lib, pkgs, modulesPath, ... }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ "amdgpu" ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/ec535af0-7a44-4c5b-b9ba-ab065114a5cb";
        fsType = "btrfs";
        options = [ "subvol=@" "compress=zstd:1" "noatime" "ssd" "space_cache=v2" "discard=async" ];
      };

    fileSystems."/home" =
      { device = "/dev/disk/by-uuid/ec535af0-7a44-4c5b-b9ba-ab065114a5cb";
        fsType = "btrfs";
        options = [ "subvol=@home" "compress=zstd:1" "noatime" "ssd" "space_cache=v2" "discard=async" ];
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/9457-B4D3";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices = [ ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.enableRedistributableFirmware = true;
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
